//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IrfanPaint.rc
//
#define IDI_DLLICON                     100
#define IDD_TOOLBOX                     100
#define IDD_ABOUT                       101
#define IDD_SELPALCOLOR                 102
#define IDD_ARROWSETTINGS               103
#define IDD_PENBRUSHSETTINGS            104
#define IDD_INSERTTEXT                  105
#define IDD_MEASUREMENTUNITS            106
#define IDD_EDITMEASUREMENTUNIT         107
#define IDD_MEASUREOUTPUT               108
#define IDC_TB_COLORPAL                 1052
#define IDC_TB_LB_WIDTH                 1053
#define IDC_TB_UD_WIDTH                 1054
#define IDC_TB_TX_WIDTH                 1055
#define IDC_TB_LB_TOLERANCE             1056
#define IDC_TB_TX_TOLERANCE             1057
#define IDC_TB_UD_TOLERANCE             1058
#define IDC_TB_CH_FILL                  1059
#define IDC_TB_TOOLBAR                  1060
#define IDC_AB_ICON                     1101
#define IDS_AB_ABOUTTRANSLATION         1101
#define IDC_AB_TEXT                     1102
#define IDC_AB_THANKS                   1103
#define IDC_AB_SITE                     1104
#define IDC_SP_CINFO                    1201
#define IDC_AS_CH_FIRST                 1301
#define IDC_AS_CH_SECOND                1302
#define IDC_AS_PREVIEW                  1303
#define IDC_AS_TX_WIDTH                 1304
#define IDC_AS_UD_WIDTH                 1305
#define IDC_AS_TX_LENGTH                1306
#define IDC_AS_UD_LENGTH                1307
#define IDC_AS_CH_OPENHEAD              1308
#define IDC_AS_L_AWIDTH                 1309
#define IDC_AS_L_ALENGTH                1310
#define IDC_AS_L_DRAW                   1311
#define IDC_PB_PREVIEW                  1401
#define IDC_PB_P_SOLID                  1404
#define IDC_PB_P_DASH                   1405
#define IDC_PB_P_DOT                    1406
#define IDC_PB_P_DASHDOT                1407
#define IDC_PB_P_DASHDOTDOT             1408
#define IDC_PB_P_CUSTOM                 1409
#define IDC_PB_P_END_ROUND              1410
#define IDC_PB_P_END_SQUARE             1411
#define IDC_PB_P_END_FLAT               1412
#define IDC_PB_P_LJ_ROUND               1413
#define IDC_PB_P_LJ_BEVEL               1414
#define IDC_PB_P_LJ_MITER               1415
#define IDC_PB_B_SOLID                  1416
#define IDC_PB_B_HHO                    1417
#define IDC_PB_B_HVE                    1418
#define IDC_PB_B_HFD                    1419
#define IDC_PB_B_HBD                    1420
#define IDC_PB_B_HCR                    1421
#define IDC_PB_B_HDI                    1422
#define IDC_PB_P_TX_CUSTOM              1423
#define IDC_PB_B_COLOR                  1424
#define IDC_PB_H_COLORP                 1425
#define IDC_PB_H_TRANSPARENT            1426
#define IDC_PB_H_COLOR                  1428
#define IDC_PB_P_IS_CUSTOM              1429
#define IDC_PB_TABS                     1430
#define IDC_PB_IS_PREVIEW               1431
#define IDC_PB_P_L_STYLE                1432
#define IDC_PB_P_L_ENDCAP               1433
#define IDC_PB_P_L_LINEJ                1434
#define IDC_PB_B_L_SOLID                1435
#define IDC_PB_B_L_LH                   1436
#define IDC_PB_B_L_45LTRH               1437
#define IDC_PB_B_L_CH                   1438
#define IDC_PB_B_L_COLOR                1439
#define IDC_PB_BOX_HSC                  1440
#define IDC_PB_BOX_BRUSH                1441
#define IDC_PB_BOX_PEN                  1442
#define IDS_PB_TABS_FG                  1443
#define IDS_PB_TABS_BG                  1444
#define IDC_PB_BOX_WIDTH                1445
#define IDC_PB_TX_WIDTH                 1446
#define IDC_PB_UD_WIDTH                 1447
#define IDC_PB_L_PIXEL                  1448
#define IDC_IT_L_FONTNAME               1501
#define IDC_IT_L_FONTSIZE               1502
#define IDC_IT_CO_FONTNAME              1503
#define IDC_IT_CO_FONTSIZE              1504
#define IDC_IT_CH_BOLD                  1506
#define IDI_IT_BOLD                     1506
#define IDC_IT_CH_ITALIC                1507
#define IDI_IT_ITALIC                   1507
#define IDC_IT_CH_UNDERLINE             1508
#define IDI_IT_UNDERLINE                1508
#define IDC_IT_CH_STRIKETHROUGH         1509
#define IDI_IT_STRIKETHROUGH            1509
#define IDC_IT_RB_ALLEFT                1510
#define IDI_IT_ALLEFT                   1510
#define IDI_IT_ALCENTER                 1511
#define IDC_IT_RB_ALCENTER              1511
#define IDC_IT_RB_ALRIGHT               1512
#define IDI_IT_ALRIGHT                  1512
#define IDC_IT_BN_SELCOLOR              1513
#define IDI_IT_SELCOLOR                 1513
#define IDC_IT_RE_TEXT                  1520
#define IDC_IT_GB_RENDERAS              1521
#define IDC_IT_RB_RA_EMPTYPATH          1522
#define IDC_IT_RB_RA_FILLEDPATH         1523
#define IDC_IT_RB_RA_TEXT               1524
#define IDC_IT_RB_RA_AATEXT             1525
#define IDC_IT_BN_PREVIEW               1526
#define IDC_MU_LV_UNITS                 1601
#define IDC_MU_BN_CLOSE                 1602
#define IDC_MU_BN_MOVEUP                1603
#define IDC_MU_BN_MOVEDOWN              1604
#define IDC_MU_BN_ABSOLUTIZE            1605
#define IDC_MU_BN_ADD                   1606
#define IDC_MU_BN_EDIT                  1607
#define IDC_MU_BN_REMOVE                1608
#define IDS_MU_NAME                     1651
#define IDS_MU_SYMBOL                   1652
#define IDS_MU_DEFINITION               1653
#define IDS_MU_DELETECONFIRM            1654
#define IDS_MU_DELETECONFIRM_CAPTION    1655
#define IDC_EMU_LB_NAME                 1701
#define IDC_EMU_TX_NAME                 1702
#define IDC_EMU_LB_SYMBOL               1703
#define IDC_EMU_TX_SYMBOL               1704
#define IDC_EMU_LB_DEFINITION           1705
#define IDC_EMU_LB_DEFINITION2          1706
#define IDC_EMU_TX_DEFINITION_COEFFICIENT 1707
#define IDC_EMU_CB_DEFINITION_SYMBOL    1708
#define IDC_MO_LS_RESULTS               1801
#define IDC_MO_BN_COPY                  1802
#define IDC_MO_BN_NEWUNIT               1803
#define IDS_ERR_CAPTION                 5000
#define IDS_ERR_SAVESETTINGSFAIL        5102
#define IDS_ERR_INVALIDLANGFILEVERSION  5103
#define IDS_ERR_NOCLONESRC              5201
#define IDS_ERR_NOTANUMBER              5301
#define IDS_ERR_EMPTY                   5302
#define IDS_THANKS                      6001
#define IDS_MUCLASS_DEFAULTUNIT         7001
#define IDS_MUCLASS_NOTDETERMINABLE     7002
#define IDS_MUCLASS_NODPI               7003
#define IDS_MUCLASS_INCH                7011
#define IDS_MUCLASS_PIXEL               7012
#define IDS_MUCLASS_DEGREE              7013
#define IDS_MUCLASS_MILLIMETER          7014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1119
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
